# Header
menu:
  homepage: /
  archives: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/dontcry2013"
  weibo: "http://weibo.com/u/2278451152"
  #rss: "http://feed.feedsky.com/litten"
  #zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
baidu_tongji: true
google_analytics: ''
favicon: /img/favicon.png

#你的头像url
avatar: "/img/litten.png"
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  三号茶馆: http://www.thirdtea.com/
  猫哥学前班: http://www.jianshu.com/users/c2f3ff613436/latest_articles

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 我是谁，我从哪里来，我到哪里去？我就是我，是颜色不一样的吃货…
